export const DESTINATION_STATE_MAP: Record<string, string> = {
  "dest-montana": "Montana",
  "dest-wyoming": "Wyoming",
  "dest-idaho": "Idaho",
  "dest-colorado": "Colorado",
  "dest-utah": "Utah",
  "dest-oregon": "Oregon",
  "dest-washington": "Washington",
  "dest-california": "California",
  "dest-alaska": "Alaska",
  "dest-michigan": "Michigan",
  "dest-pennsylvania": "Pennsylvania",
  "dest-new-jersey": "New Jersey",
  "dest-arkansas": "Arkansas",
  "dest-arizona": "Arizona",
  "dest-new-mexico": "New Mexico",
  "dest-tennessee": "Tennessee",
  "dest-north-carolina": "North Carolina",
  "dest-virginia": "Virginia",
  "dest-west-virginia": "West Virginia",
  "dest-kentucky": "Kentucky",
  "dest-georgia": "Georgia",
  "dest-new-york": "New York",
  "dest-vermont": "Vermont",
  "dest-maine": "Maine",
  "dest-texas": "Texas",
  "dest-washington-dc-area": "Maryland",
  "dest-connecticut": "Connecticut",
  "dest-massachusetts": "Massachusetts",
  "dest-wisconsin": "Wisconsin",
  "dest-minnesota": "Minnesota",
  "dest-nevada": "Nevada",
};
