export const US_STATES = [
  { name: "Alaska", abbrev: "AK", center: [-153, 64] as [number, number], zoom: 4 },
  { name: "Arizona", abbrev: "AZ", center: [-111.5, 34] as [number, number], zoom: 6 },
  { name: "Arkansas", abbrev: "AR", center: [-92.4, 34.8] as [number, number], zoom: 7 },
  { name: "California", abbrev: "CA", center: [-119.5, 37.5] as [number, number], zoom: 5.5 },
  { name: "Colorado", abbrev: "CO", center: [-105.5, 39] as [number, number], zoom: 6.5 },
  { name: "Connecticut", abbrev: "CT", center: [-72.7, 41.6] as [number, number], zoom: 8.5 },
  { name: "Florida", abbrev: "FL", center: [-81.5, 27.5] as [number, number], zoom: 6 },
  { name: "Georgia", abbrev: "GA", center: [-83.5, 32.5] as [number, number], zoom: 6.5 },
  { name: "Idaho", abbrev: "ID", center: [-114.5, 44.5] as [number, number], zoom: 6 },
  { name: "Kentucky", abbrev: "KY", center: [-84.9, 37.5] as [number, number], zoom: 7 },
  { name: "Maine", abbrev: "ME", center: [-69.5, 45.5] as [number, number], zoom: 7 },
  { name: "Maryland", abbrev: "MD", center: [-76.5, 39.5] as [number, number], zoom: 7.5 },
  { name: "Massachusetts", abbrev: "MA", center: [-71.5, 42.2] as [number, number], zoom: 8 },
  { name: "Michigan", abbrev: "MI", center: [-84.5, 44.5] as [number, number], zoom: 6 },
  { name: "Minnesota", abbrev: "MN", center: [-93, 46] as [number, number], zoom: 6 },
  { name: "Montana", abbrev: "MT", center: [-109.5, 47] as [number, number], zoom: 6 },
  { name: "Nevada", abbrev: "NV", center: [-116.5, 39.5] as [number, number], zoom: 6 },
  { name: "New Mexico", abbrev: "NM", center: [-106, 34.5] as [number, number], zoom: 6.5 },
  { name: "New York", abbrev: "NY", center: [-75.5, 42.5] as [number, number], zoom: 6.5 },
  { name: "North Carolina", abbrev: "NC", center: [-79.5, 35.5] as [number, number], zoom: 6.5 },
  { name: "Oregon", abbrev: "OR", center: [-120.5, 43.5] as [number, number], zoom: 6 },
  { name: "Pennsylvania", abbrev: "PA", center: [-77.5, 41] as [number, number], zoom: 7 },
  { name: "South Dakota", abbrev: "SD", center: [-100, 44.5] as [number, number], zoom: 6.5 },
  { name: "Tennessee", abbrev: "TN", center: [-86, 35.8] as [number, number], zoom: 6.5 },
  { name: "Texas", abbrev: "TX", center: [-99, 31] as [number, number], zoom: 5.5 },
  { name: "Utah", abbrev: "UT", center: [-111.5, 39.5] as [number, number], zoom: 6.5 },
  { name: "Vermont", abbrev: "VT", center: [-72.5, 44] as [number, number], zoom: 7.5 },
  { name: "Virginia", abbrev: "VA", center: [-79, 37.5] as [number, number], zoom: 6.5 },
  { name: "Washington", abbrev: "WA", center: [-120.5, 47.5] as [number, number], zoom: 6.5 },
  { name: "West Virginia", abbrev: "WV", center: [-80.5, 38.5] as [number, number], zoom: 7 },
  { name: "Wisconsin", abbrev: "WI", center: [-90, 44.5] as [number, number], zoom: 6.5 },
  { name: "Wyoming", abbrev: "WY", center: [-107.5, 43] as [number, number], zoom: 6.5 },
];
