/**
 * Executive Angler icon names — v4.1 §16.
 * Desk metaphors plus chrome marks. A typo is a type error.
 */

export const ICON_NAMES = [
  "activity",
  "angler",
  "aperture",
  "arrow-left",
  "arrow-right",
  "arrow-up-right",
  "at",
  "ban",
  "bell",
  "box",
  "branch",
  "building",
  "camera",
  "check",
  "check-double",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "chevron-up",
  "clock",
  "close",
  "cloud",
  "compass",
  "copy",
  "creel",
  "crop",
  "current",
  "database",
  "download",
  "external",
  "eye",
  "eye-off",
  "facebook",
  "filter",
  "flag",
  "flame",
  "gauge",
  "grid",
  "grip",
  "hackle",
  "hatch",
  "heart",
  "help",
  "home",
  "hook",
  "images",
  "info",
  "instagram",
  "key",
  "layers",
  "leaf",
  "library",
  "link",
  "linkedin",
  "list",
  "live",
  "loader",
  "lock",
  "login",
  "logout",
  "mail",
  "map",
  "medal",
  "menu",
  "message",
  "minus",
  "more",
  "more-vertical",
  "notebook",
  "package",
  "pencil",
  "phone",
  "pin",
  "play",
  "plus",
  "printer",
  "refresh",
  "repeat",
  "rule",
  "save",
  "search",
  "send",
  "settings",
  "share",
  "shield",
  "social-x",
  "sort",
  "split",
  "star",
  "store",
  "sunrise",
  "swap",
  "table",
  "thumbs-up",
  "ticket",
  "timer",
  "trash",
  "type",
  "undo",
  "upload",
  "user-check",
  "user-minus",
  "user-plus",
  "vise",
  "warning",
  "wind",
  "youtube",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

const ICON_NAME_SET: ReadonlySet<string> = new Set(ICON_NAMES);

export function isIconName(value: string): value is IconName {
  return ICON_NAME_SET.has(value);
}

/** Small-caps fallback for a missing name — never a broken square. */
export function iconMark(name: string): string {
  const compact = name.replace(/[^a-z0-9]/gi, "");
  if (!compact) return "EA";
  return compact.slice(0, 3).toUpperCase();
}

/**
 * Lucide export names → desk set. Banned metaphors (sparkle, chart-up,
 * users-three, generic pin, glowing bolt, rocket) map onto desk drawings.
 */
export const LUCIDE_TO_ICON = {
  Activity: "current",
  AlertCircle: "warning",
  AlertTriangle: "warning",
  Anchor: "hook",
  Aperture: "aperture",
  ArrowLeft: "arrow-left",
  ArrowRight: "arrow-right",
  ArrowRightLeft: "swap",
  ArrowUpDown: "sort",
  ArrowUpRight: "arrow-up-right",
  AtSign: "at",
  Award: "creel",
  Ban: "ban",
  BarChart3: "gauge",
  Bell: "bell",
  BookOpen: "notebook",
  Box: "box",
  Boxes: "box",
  Bug: "hackle",
  Building: "building",
  Calendar: "hatch",
  Camera: "camera",
  Check: "check",
  CheckCheck: "check-double",
  CheckCircle: "check",
  CheckCircle2: "check",
  ChevronDown: "chevron-down",
  ChevronLeft: "chevron-left",
  ChevronRight: "chevron-right",
  ChevronUp: "chevron-up",
  Clock: "clock",
  Cloud: "cloud",
  CloudSun: "cloud",
  Compass: "compass",
  Copy: "copy",
  Crop: "crop",
  Database: "database",
  DollarSign: "rule",
  Download: "download",
  Droplets: "current",
  Edit2: "pencil",
  Edit3: "pencil",
  ExternalLink: "external",
  Eye: "eye",
  EyeOff: "eye-off",
  Feather: "hackle",
  FileEdit: "pencil",
  FileSpreadsheet: "table",
  FileText: "notebook",
  Filter: "filter",
  Fish: "hook",
  FishSymbol: "hook",
  Flag: "flag",
  Flame: "flame",
  FlipHorizontal: "swap",
  Gauge: "gauge",
  GitBranch: "branch",
  GitFork: "branch",
  Globe: "map",
  Grid3X3: "grid",
  GripVertical: "grip",
  Heart: "heart",
  HelpCircle: "help",
  Home: "home",
  Image: "images",
  Images: "images",
  Info: "info",
  Instagram: "instagram",
  KanbanSquare: "grid",
  Key: "key",
  Layers: "layers",
  LayoutDashboard: "grid",
  LayoutGrid: "grid",
  Leaf: "leaf",
  Library: "library",
  Lightbulb: "info",
  Link: "link",
  Link2: "link",
  Linkedin: "linkedin",
  List: "list",
  ListChecks: "list",
  Loader2: "loader",
  Lock: "lock",
  LogIn: "login",
  LogOut: "logout",
  Mail: "mail",
  MapPin: "map",
  Medal: "medal",
  Menu: "menu",
  MessageCircle: "message",
  MessageSquare: "message",
  MessageSquarePlus: "message",
  Minus: "minus",
  MoreHorizontal: "more",
  MoreVertical: "more-vertical",
  Mountain: "map",
  Newspaper: "notebook",
  Package: "package",
  Pencil: "pencil",
  Phone: "phone",
  Pin: "map",
  Play: "play",
  Plus: "plus",
  Printer: "printer",
  Radio: "live",
  RefreshCw: "refresh",
  Repeat: "repeat",
  RotateCcw: "undo",
  RotateCw: "refresh",
  Rows3: "list",
  Ruler: "rule",
  Save: "save",
  Search: "search",
  Send: "send",
  Settings: "settings",
  Share2: "share",
  Shield: "shield",
  ShoppingBag: "store",
  SlidersHorizontal: "vise",
  Sparkles: "hackle",
  Split: "split",
  Star: "star",
  StickyNote: "notebook",
  Store: "store",
  Sunrise: "sunrise",
  Table: "table",
  Target: "gauge",
  Thermometer: "gauge",
  ThumbsUp: "thumbs-up",
  TicketPercent: "ticket",
  Timer: "timer",
  Trash2: "trash",
  TrendingDown: "current",
  TrendingUp: "current",
  Trophy: "creel",
  Twitter: "social-x",
  Type: "type",
  Undo2: "undo",
  Upload: "upload",
  User: "angler",
  UserCheck: "user-check",
  UserPlus: "user-plus",
  Users: "angler",
  UserX: "user-minus",
  Wand2: "hackle",
  Waves: "current",
  Wind: "wind",
  Wrench: "vise",
  X: "close",
  XCircle: "close",
  Youtube: "youtube",
} as const satisfies Record<string, IconName>;

export type LucideExportName = keyof typeof LUCIDE_TO_ICON;
